convert millis to seconds
```console
$ cargo run --config ui.streampager.long-or-slow-delay-seconds=1.1 --config ui.streampager.interface=\"quit-quickly-or-clear-outpu\" log
error: failed to convert --config argument `ui.streampager.long-or-slow-delay-seconds=1.1`

Caused by:
  failed to parse key `ui`

Caused by:
  failed to parse key `streampager`

Caused by:
  failed to parse key `long-or-slow-delay-seconds`

Caused by:
  found TOML configuration value of unknown type `float`
```